OCAMLMAKEFILE=OCamlMakefile
RESULT=binomial

SOURCES=base64.mli base64.ml cref.mli cref.ml cmd.ml cwt.mli cwt.ml binomial.ml

ANNOTATE=yes

PACKS += unix
PACKS += yojson

LIBS += delimcc

all: dc
	@ :

-include $(OCAMLMAKEFILE)
