OCAMLMAKEFILE=OCamlMakefile
RESULT=ocamltest

SOURCES=base64.mli base64.ml cref.mli cref.ml cmd.ml cwt.mli cwt.ml test.ml

ANNOTATE=yes

PACKS += unix
PACKS += yojson

LIBS += delimcc

all: nc
	@ :

-include $(OCAMLMAKEFILE)
