Document: ciel
Title: Debian ciel Manual
Author: <insert document author here>
Abstract: This manual describes what ciel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ciel/ciel.sgml.gz

Format: postscript
Files: /usr/share/doc/ciel/ciel.ps.gz

Format: text
Files: /usr/share/doc/ciel/ciel.text.gz

Format: HTML
Index: /usr/share/doc/ciel/html/index.html
Files: /usr/share/doc/ciel/html/*.html
