#!/bin/bash
# Copyright (c) 2010 Malte Schwarzkopf <malte.schwarzkopf@cl.cam.ac.uk>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# ----
#
# Non-graceful cluster shutdown script.
#
# usage: See sw-kill-cluster -h

# defaults
KEY="sw-masterkey"
SWUSER="root"
SWROOT="/opt/skywriting"
VERBOSE=0

# ---------------------------------------------
# option processing

while [ $# -gt 0 ]
do
  case $1
  in
    -v)
      VERBOSE=1
      shift 1
    ;;

    -i|-k)
      KEY=$2
      shift 2
    ;;

    -f)
      if [[ $2 = '--' ]]; then
         # STDIN input
         SOURCE='/dev/stdin'
      else
         # Cluster definition file
         SOURCE=$2
      fi
      shift 2
    ;;
    
    -u|--swuser)
      SWUSER=$2
      shift 2
    ;;

    -h|*)
      echo "usage: sw-kill-cluster [-f cluster-file|(-i|-k) key|-u swuser|-v]"
      echo "-f: the file listing the machines in the cluster, one per line."
      echo "    If '--' is passed, STDIN is assumed."
      echo "-i|-k: the private key to use for authentication to cluster machines"
      echo "       (defaults to 'sw-masterkey')"
      echo "-u|--swuser: the user name of the Skywriting user on the cluster"
      echo "             (defaults to 'root')"
      echo "-v: verbose mode (don't surpress output from remote machines)"
      shift 1
      exit 0
    ;;
  esac
done

# ---------------------------------------------
# main script

I=0
exec 3<$SOURCE
while read -u 3 myLine
do
    echo -n "Killing instance $I: "
    
    # To explain that ridiculous command: pgrep for the tag inserted into all Ciel commands' args by run_master/worker. Then use 'ps' to translate that line of PIDs
    # into line-delimited pgrps. Then use pkill to zap anything sharing a group with any of them with signal 9.
    # This handles both daemonised and non-daemonised cases, in which the relevant group is and isn't respectively the group of the root Python process.
    if [[ $VERBOSE -eq 1 ]]; then
	ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine $SWROOT/scripts/ciel-killall.sh
    else
	ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine $SWROOT/scripts/ciel-killall.sh 1>&2 2>/dev/null
    fi
    echo $myLine
    I=`expr $I + 1`
done

exit 0
