#!/usr/bin/python

import skywriting.runtime.util.start_job
from shared.references import SWErrorReference,SWDataValue
import sys

done = skywriting.runtime.util.start_job.wait()

if done:
	sys.exit(0)
else:
	sys.exit(1)