#!/bin/bash

# defaults
KEY="sw-masterkey"
SWUSER="root"
SWROOT="/opt/skywriting"
VERBOSE=0

# ---------------------------------------------
# option processing

while [ $# -gt 0 ]
do
  case $1
  in
    -v)
      VERBOSE=1
      shift 1
    ;;

    -i|-k)
      KEY=$2
      shift 2
    ;;

    -f)
      if [[ $2 = '--' ]]; then
         # STDIN input
         SOURCE=/dev/stdin
      else
         # Cluster definition file
         SOURCE=$2
      fi
      shift 2
    ;;
    
    -r|--swroot)
      SWROOT=$2
      shift 2
    ;;
    
    -u|--swuser)
      SWUSER=$2
      shift 2
    ;;
    
    -w|--wipejournal)
      WIPEJOURNAL=1
      shift 1
    ;;

    -h|*)
      echo "usage: sw-launch-cluster [-f cluster-file|(-i|-k) key|-r swroot|-u swuser|-v]"
      echo "-f: the file listing the machines in the cluster, one per line."
      echo "    If '--' is passed, STDIN is assumed."
      echo "-i|-k: the private key to use for authentication to cluster machines"
      echo "       (defaults to 'sw-masterkey')"
      echo "-r|--swroot: the root directory of the remote Skywriting installation"
      echo "             (defaults to '/opt/skywriting')"
      echo "-u|--swuser: the user name of the Skywriting user on the cluster"
      echo "             (defaults to 'root')"
      echo "-v: verbose mode (don't surpress output from remote machines)"
      echo "-w|--wipejournal: wipe the job journal on the master before launching it"
      shift 1
      exit 0
    ;;
  esac
done

# ---------------------------------------------
# main script

I=0
cat $SOURCE | while myLine=`line`
do
    echo -n "Setting up instance $I "
    if [ "$I" -eq "0" ]; then
	echo "... as a master."
	if [[ $VERBOSE -eq 1 ]]; then
	    if [[ $WIPEJOURNAL -eq 1 ]]; then
		ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine "rm -rf $SWROOT/journal/*"
	    fi
	    ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine "export PYTHONPATH=$SWROOT/src/python/ ; export CLASSPATH=$SWROOT/src/java/JavaBindings.jar ; $SWROOT/scripts/sw-master -p 8000 -j $SWROOT/journal/ 2>&1 | tee $SWROOT/logs/master.log"
	else
	    if [[ $WIPEJOURNAL -eq 1 ]]; then
		ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine "rm -rf $SWROOT/journal/*"
	    fi
	    ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine "export PYTHONPATH=$SWROOT/src/python/ ; export CLASSPATH=$SWROOT/src/java/JavaBindings.jar ; $SWROOT/scripts/sw-master -p 8000 -j $SWROOT/journal/ 2>&1 | tee $SWROOT/logs/master.log" 1>/dev/null
	fi
	MASTER=$myLine
    else
	echo "... as a worker for $MASTER"
	if [[ $VERBOSE -eq 1 ]]; then
	    ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine "export PYTHONPATH=$SWROOT/src/python/ ; export CLASSPATH=$SWROOT/src/java/JavaBindings.jar ; $SWROOT/scripts/sw-worker -m 'http://$MASTER:8000' -p 8001 2>&1 | tee $SWROOT/logs/worker.log"
	else
	    ssh -o StrictHostKeyChecking=no -f -i $KEY $SWUSER@$myLine "export PYTHONPATH=$SWROOT/src/python/ ; export CLASSPATH=$SWROOT/src/java/JavaBindings.jar ; $SWROOT/scripts/sw-worker -m 'http://$MASTER:8000' -p 8001 2>&1 | tee $SWROOT/logs/worker.log" 1>/dev/null
	fi
    fi
    I=`expr $I + 1`
done

exit 0
