#!/usr/bin/python

import skywriting.runtime.util.start_job
from shared.references import SWErrorReference,SWDataValue
import sys

result = skywriting.runtime.util.start_job.main()

print "========"
print "Script result:", result
