#!/usr/bin/python

import skywriting.runtime.util.start_job
from shared.references import SWErrorReference,SWDataValue
import sys

result = skywriting.runtime.util.start_job.main()

if isinstance(result, SWErrorReference):
    retcode=1
    print >> sys.stderr, result
elif isinstance(result, SWDataValue):
    retcode=0
    print result.value
else:
    retcode=2
    print >> sys.stderr, result

exit(retcode)
